class FichaTecnica:
    def __init__(self, data):
        self.idrows = data.get("IdRows")
        self.referencia = data.get("ReferenciaFTec")
        self.ref_cliente = data.get("ReferenciaCliFTec")
        self.ano = data.get("AnoFTec")
        self.mes = data.get("NomMesFTec")
        self.campana = data.get("CampanaFTec")
        self.prendas = data.get("PrendasFTec")
        self.pintas = data.get("PintasFTec")
        self.empaque = data.get("EmpaqueFTec")
        self.prototipo = data.get("PrototipoFTec")
        self.muestra_fis = data.get("MuestraFisFtec")
        self.tipo_estamp = data.get("TipoEstampFTec")
        self.ref_molderia = data.get("RefMolderiaFTec")
        self.piezas_molderia = data.get("PiezasMoldFT")
        self.archivo_diseno = data.get("ArchivoDisenoFTec")
        self.tallas = data.get("TallasFT")
        self.composicion_prenda = data.get("ComposicionPrenda")
        self.canal = data.get("NombreCan")
        self.cliente = data.get("NombreCli")
        self.disenador = data.get("NombreDis")
        self.responsable = data.get("NombreResp")
        self.estado = data.get("NombreEst")
        self.estampacion = data.get("NombreEstEstam")
        self.est_insumos = data.get("NombreEstIns")
        self.est_molderia = data.get("NombreEstMol")
        self.est_procesos = data.get("NombreEstPrc")
        self.genero = data.get("NombreGen")
        self.licencia = data.get("NombreLic")
        self.linea = data.get("NombreLin")
        self.tipo_prenda = data.get("NombreTipPrn")
        self.silueta = data.get("SiluetaF")
        self.tejido = data.get("NombreTipTej")
        self.ropero = data.get("RoperoFTec")
        self.ruta_imagen = data.get("RutaImagen")
        self.ruta_imagen_2 = data.get("RutaImagen2")
        self.procesos = data.get("ProcesosFTec")
        self.referencia_base = data.get("ReferenciaBasFTec")
        self.idrow_digital_ocean = data.get("IdRowDigitalOcean")
        self.fecha_insercion = data.get("FechaInsercion")

    def to_dict(self):
        return self.__dict__